### ISSUE TITLE
RedisBungee Support

### ISSUE THREAD

**Issue by ShadowChildUK** [jamezrin/PlayerBalancer#12]
Add support for RedisBungee to assist with better balancing on multi-proxy setups.

**Comment by jamezrin** [comment]
I am not going to waste my time adding it back, since the repository for its API was taken down. 
If someone finds a repo containing RedisBungee's API, maybe I will consider it.

**Comment by galexrt** [comment]
RedisBungee was forked by "limework"/"ProxioDev" so it might be feasible to see if it makes sense to re-add/re-implement the code using the fork: https://github.com/ProxioDev/RedisBungee

As far as I can tell it should be "backwards compatible".

**Comment by BGHDDevelopment** [comment]
Support was added back 2 updates ago.

**Comment by galexrt** [comment]
@BGHDDevelopment My bad, I haven't gotten the Spigot update emails :smile: Thanks for that!
