### ISSUE TITLE
Error on server kick

### ISSUE THREAD

**Issue by goinpierreolivier** [jamezrin/PlayerBalancer#14]
Hello,
I'm running the latest version of this plugin, and I'm using the latest version of Waterfall (https://share.koora.eu/fvCR2NJPuG.png).
But when I was kicked from the server, I get this error in the console (https://share.koora.eu/fn1q49etuu.txt).

I send you the config file. (https://share.koora.eu/9WUgtQQqWa.conf)

And, btw, It dont send me to general lobbies :/

Thanks.

**Comment by jamezrin** [comment]
Hi, doesn't the plugin complain in the console? You don't have any provider set, there are some examples in the default configuration file

**Comment by jamezrin** [comment]
https://github.com/jamezrin/PlayerBalancer/blob/master/balancer/src/main/resources/default.conf

**Comment by goinpierreolivier** [comment]
1. No, It doesnt complain in the console, I send you some full n fresh logs! (https://share.koora.eu/C0P1CRh2m3.txt)
2. For the provider, I'll give a shot!
