### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Feerko** [jamezrin/PlayerBalancer#5]
hey, playerbalancer has a memory leak. 

<img width="630" alt="zrzut ekranu 2018-12-30 o 00 44 36" src="https://user-images.githubusercontent.com/16988054/50543072-63f8e280-0bcc-11e9-9cf3-1369b7ec59df.png">

**Comment by jamezrin** [comment]
Uhm, that's trange. I'm wondering if the tool you are using could get more specific.
I'm looking into this but I have to know a few things:

- Which version of BungeeCord and PlayerBalancer are you running?
- Did you use /balancer reload?. If so, were there any errors?

**Comment by Feerko** [comment]
Hey, I never use reload. Always restart and there is no errors. I use the latest version of Waterfall and PlayerBalancer

.

**Comment by jamezrin** [comment]
I think I might know where it might be happening, do you have the `server-checker` tactic set to `CUSTOM`?
If so, try setting it to GENERIC (it will use the one BungeeCord provides) and see if it still happens.

**Comment by jamezrin** [comment]
Sorry but I want to clarify, does it still happen with it set to `GENERIC`?
I assumed it would take a bit for you to test that, the commit I added is not guaranteed to fix anything. I don't know if the problem is actually there or not.
Thanks.

**Comment by Feerko** [comment]
Ok, today I will make a dump of memory of the old version. Tomorrow I will change the server-checker to generic. The day after tomorrow I will check your commit. 

So it should take about 2 days and I will let you know about the results.

**Comment by jamezrin** [comment]
Perfect, I'm looking forward to see the results. Thanks.

**Comment by Feerko** [comment]
hi, I tried with two server-checker types. The same result. I also tested your new commit.
<img width="852" alt="zrzut ekranu 2019-01-2 o 10 31 41" src="https://user-images.githubusercontent.com/16988054/50586424-a4c95380-0e79-11e9-9b0d-1022fa8532f4.png">
<img width="843" alt="zrzut ekranu 2019-01-2 o 10 33 04" src="https://user-images.githubusercontent.com/16988054/50586460-cfb3a780-0e79-11e9-9961-bab8609f819f.png">

I tested your new commit. Returns 0/0 players in section.

**Comment by jamezrin** [comment]
Ok, that image actually tells me everything I needed to know.
As you experienced the problem isn't what I thought it was.

The problem with the sections is caused by other commit that wasn't on the latest release of PlayerBalancer. That commit (49c64bb1cdb08719e97dc089ae8680f3f1ed15a5) was a mess and I think it was actually because other user reported the same issue you did, but we never got to know where it was originated from.

I'm going to revert that commit and fix the memory leak.

**Comment by jamezrin** [comment]
I'm pretty sure that commit will fix that issue, the image you sent me was pretty useful.
Please let me know if that fixes the issue and I'll merge it. Thanks.

**Comment by Feerko** [comment]
Hello, memory still leaks, result from the whole day:

<img width="833" alt="zrzut ekranu 2019-01-3 o 22 57 30" src="https://user-images.githubusercontent.com/16988054/50663774-0e954a80-0fab-11e9-95c6-dfa1f11ddac5.png">

<img width="847" alt="zrzut ekranu 2019-01-3 o 22 57 43" src="https://user-images.githubusercontent.com/16988054/50663776-11903b00-0fab-11e9-82a0-a484724ff6c1.png">

**Comment by jamezrin** [comment]
[Build.zip](https://github.com/jamezrin/PlayerBalancer/files/2725504/Build.zip)

**Comment by Feerko** [comment]
I know how to compile, I just chose wrong branch. Everything works great now.
Thank you for your help :)
