### ISSUE TITLE
Error when the plugin loading

### ISSUE THREAD

**Issue by HappyAreaBean** [jamezrin/PlayerBalancer#8]
Error code: https://hastebin.com/uturihoqoh.rb

**Comment by jamezrin** [comment]
The paste is empty, I cannot see the error.

**Comment by HappyAreaBean** [comment]
> The paste is empty, I cannot see the error.

hm. let me place once again 
https://privatebin.net/?972cc121a7e16224#9oJYev7GXP7nPjbKpfQF8VqhxFkrEMwDiDv2YJJ4GHt6

**Comment by jamezrin** [comment]
Which version of bungeecord are you running? And of playerbalancer?

**Comment by JuanFerGamerYT** [comment]
I have the same error, I use Flamecord, its a fork of bungee, and PlayerBalancer 2.1.6.1

**Comment by jamezrin** [comment]
Tell me the version of BungeeCord or Flamecord, I need to know...
A screenshot of /bungee should work.

**Comment by jamezrin** [comment]
Closed for not providing issue information.
